language: go

go:
 - "1.4"
 - "1.5"
 - "1.6"
 - "1.7"
 - "1.8"
 - "1.9"
 - "1.10"
 - "1.11"
 - "1.12"
 - "1.13"
 - "1.14"

before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
 - sudo apt-get install xsel
 - go test -v .
 - sudo apt-get install xclip
 - go test -v .
